### PR TITLE
ci: removed conventional-changelog as version script

### PR DESCRIPTION
**Pull request by enell**

### CODE REVIEW

**Review by cbt1 — APPROVED** [review]
I know you mentioned it eariler today but why did you have to remove the changelog?

**Comment by enell** [comment]
> I know you mentioned it eariler today but why did you have to remove the changelog?

Cangelog file isn't generated in the new release flow. It is instead added in each release object in GitHub

**Review by a-m-dev — APPROVED** [review]

**Comment by cbt1** [comment]
@enell Are you gonna merge this one?

**Pull request merged**
