### PR TITLE
feat: base provider

### PR DESCRIPTION
**Pull request by cbt1**

### CODE REVIEW

**Comment by haxxmaxx** [comment]
Feels like these props are passed to components which shouldn't be needed anymore? Are you starting to use the provider in the next PR?

**Comment by haxxmaxx** [comment]
sorry wrong button

**Comment by cbt1** [comment]
> Feels like these props are passed to components which shouldn't be needed anymore? Are you starting to use the provider in the next PR?

Yes. Two new PR:s are coming after this one.

First which enabled the header menu selections. It's using the `app`, `model` and `interactions` on a component cell level. So lots of prop drilling there.

Second is a refactoring where `constraints` is replace with `interactions`. Which affects the `DimensionCell` component an all it's parent components.

**Review by a-m-dev — APPROVED** [review]

**Pull request merged**
